<h1 class="cushycms">Who are you?!</h1>
    <div class="text cushycms"><p><b>Simply put OT WikiFlash is YOU!. If you make a contribution then you are part of it!</b></p>
<p>OTWikiFlash was a mad idea drawn up in 2008 by the UK arm of the &quot;OT On The Net&quot; group. This is a group of like minded OTs who are keen on getting OTs using web tools to share and spread information relating to the profession and help foster communication betweeen clinicans</p>
<p>The UK arm met fully for the first time last year after their presentation at the UK College of Occupational Therapy National Conference which was entirely made over the net with the help of some other essential worldwide collaborators. Somewhat excited after the talk we were wondering &quot;What Next??!&quot; and the OTWikiFlash was the first of the many ideas that came out from sitting on the conference floor. OTWikiFlash 08 was a great sucess and we are aiming to be bigger and better.</p>
<p><a name="title"></a><b>Where does the wierd name come from?</b>The idea was to do something for OT week that a) reached the masses b) made a difference to everybody c) Was a easy introduction for OTs unfamiliar to the Net to get involved. It was generally considered that Wikipedia would be a great starting point and it was thought the idea of Mob Flashing (an event where people get to get together for one specific moment to do something, e.g. a pillow fight, in a public place, and organised over the internet) seemed to work nicely. The name just fitted!</p>
<p><b>Credits:</b></p>
<p><b>Will Wade.</b> A research OT from Oxford, UK and in a past life a web developer for companies such as the BBC. Will is editor of the resource blog site <a href="http://metaot.com">meta-ot</a> and a number of other &quot;in development&quot; web applications for OTs. He is incredibly enthusiastic that OTs have an altruistic behaviour to information knowledge and sharing information for the greater good.</p>
<p><b>Sarah Bodell.</b>&nbsp;One half of &quot;team Frederick Road&quot;, Sarah is a OT currently working at Salford University alongside Angela Hook. Both Sarah &amp; Angela's interest in web technologies have been born out of their development of the first entirely online Masters programme in OT. Sarah is the proud owner of a iphone.</p>
<p><b>Angela Hook.</b> The other half of &quot;team Frederick Road&quot;. Sarah &amp; Angela run the popular and busy blog at <a href="http://www.frederickroad.blogspot.com">www.frederickroad.blogspot.com</a>. Amongst other things Angela loves holidays</p>
<p><b>And the rest of you..</b> OT bloggers, educators, OT associations...You know who you are!</p></div>