<h1 class="cushycms">&quot;What is this Wikipedia nonsense?&quot; and more answers to your questions..</h1>
    <div class="text cushycms"><p><b>&quot;Wikipedia is a free, multilingual, open content encyclopedia project operated by the non-profit Wikimedia Foundation. Its name is a portmanteau of the words wiki (a technology for creating collaborative websites) and encyclopedia. Wikipedia's 10 million articles, about a quarter of which are in English, have been written collaboratively by volunteers around the world, and nearly all of its articles can be edited by anyone who can access the Wikipedia website&quot; (Wikipedia, 2009) </b></p>
<p><img class="signup floatleft" src="/images/commoncraft.jpg" alt="" />The above is taken directly from wikipedia. Put simply its a encyclopaedia that is edited by <b>YOU</b>! If you see something wrong or a page is missing something crucial fact (or is blatantly wrong) make the difference to put it right! To understand how a wiki works take a look at the video to the left</p>
<br />
<p>Here are some more questions you may be asking yourself?</p>
<p>&nbsp;</p>
<ol>
    <li><b>Why should I share my information to the world?! It's taken me a long time to learn this!</b> Would you like others to spend the same amount of time you have taken to learn your information? In the future would you like to spend less time searching and trying to find the correct and accurate information? Sharing is good.</li>
    <li><b>I want to be credited for my work</b> Note that everything you do in wikipedia is written to the system as an edit by YOU. Just as someone can look up a piece of infactual information and credit it to you so users can see who has made a factual piece of information. If you have some really juicy unique information I would suggest that Wikipedia may not be the place for this information. Another solution may be around the corner however..</li>
    <li><b>Arrgh! I have gone and told my students not to use Wikipedia - what will this tell them?</b> I don't want to be the one to break this to you but heck, its actually OK to use sources of information on the internet. Its just important that students (and clinicians) check their information and be confident of using it in the right context</li>
    <li><b>How will you keep track of a large number of edits></b> Now thats a good question. We hope to keep a close eye on the pages and help the cleaning up process as we go.</li>
</ol>
<p>&nbsp;</p></div>

<div id="modalwikivideo" style="display:none;"><object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/-dnL00TdmLY&hl=en&fs=1"></param><param name="allowFullScreen" value="true"></param><embed src="http://www.youtube.com/v/-dnL00TdmLY&hl=en&fs=1" type="application/x-shockwave-flash" allowfullscreen="true" width="425" height="344"></embed></object></div>